/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.edusys.ul;

import com.edusys.dao.UserDao;
import com.edusys.entity.User;
import com.edusys.utils.Auth;
import com.edusys.utils.MsgBox;
import com.edusys.utils.XImage;
import java.awt.Color;
import javax.swing.border.EmptyBorder;
import javax.swing.border.MatteBorder;

/**
 *
 * @author hoang
 */
public class DangNhapDialog extends javax.swing.JDialog {
 UserDao dao = new UserDao();
    /**
     * Creates new form DangNhapDialog
     */
    public DangNhapDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtTenDN.setBorder(new EmptyBorder(20, 3, 10, 3));
        txtTenDN.setBorder(new MatteBorder(0, 0, 1, 0, new Color(0, 153, 255)));
        
        txtMatKhau.setBorder(new EmptyBorder(20, 3, 10, 3));
        txtMatKhau.setBorder(new MatteBorder(0, 0, 1, 0, new Color(0, 153, 255)));

    }
      void init() {
        setIconImage(XImage.getAppIcon());
        setLocationRelativeTo(null);
        setTitle("ĐĂNG NHẬP");
    }

    void ketThuc() {
        if (MsgBox.confirm(this, "Bạn muốn kết thúc ứng dụng")) {
            System.exit(0);
        }
    }

    void dangNhap() {
        String strTenDN = txtTenDN.getText();
        String strPassword = new String(txtMatKhau.getPassword());
        User nv = dao.selectById(strTenDN);
        if (nv == null) {
            MsgBox.alert(this, "Sai Tên Đăng Nhập");
        } else {
            if (!nv.getMatKhau().equals(strPassword)) {
                MsgBox.alert(this, "Sai Mật Khẩu");
            } else {
                MsgBox.alert(this,"Đăng nhập thành công");
                Auth.user = nv;
                this.dispose();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTenDN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        pnSignIn = new javax.swing.JPanel();
        lblSignIn = new javax.swing.JLabel();
        lblForgot = new javax.swing.JLabel();
        lblketthuc = new javax.swing.JLabel();
        lblSignIn1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(900, 560));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 560));
        jPanel1.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/lg (1).png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 20, 260, 220);

        jLabel9.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Welcome Back  To");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 240, 264, 80);

        jLabel11.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("DRINK DROP");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 290, 352, 80);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 560);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN IN");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(580, 70, 150, 48);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Username:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(440, 160, 100, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/user.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(820, 190, 32, 40);

        txtTenDN.setBackground(new java.awt.Color(255, 255, 255));
        txtTenDN.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtTenDN.setForeground(new java.awt.Color(0, 153, 255));
        jPanel2.add(txtTenDN);
        txtTenDN.setBounds(440, 190, 420, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Password:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(440, 260, 100, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/password.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(820, 290, 40, 40);

        txtMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMatKhau.setForeground(new java.awt.Color(0, 153, 255));
        txtMatKhau.setMargin(new java.awt.Insets(2, 10, 2, 6));
        jPanel2.add(txtMatKhau);
        txtMatKhau.setBounds(440, 290, 420, 40);

        pnSignIn.setBackground(new java.awt.Color(0, 153, 255));
        pnSignIn.setMaximumSize(new java.awt.Dimension(320, 60));
        pnSignIn.setLayout(null);

        lblSignIn.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblSignIn.setForeground(new java.awt.Color(255, 255, 255));
        lblSignIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignIn.setText("SIGN IN");
        lblSignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSignInMouseExited(evt);
            }
        });
        pnSignIn.add(lblSignIn);
        lblSignIn.setBounds(0, 0, 320, 60);

        jPanel2.add(pnSignIn);
        pnSignIn.setBounds(490, 430, 320, 60);

        lblForgot.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblForgot.setForeground(new java.awt.Color(0, 0, 0));
        lblForgot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblForgot.setText("Forgot Password?");
        lblForgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblForgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblForgotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblForgotMouseExited(evt);
            }
        });
        jPanel2.add(lblForgot);
        lblForgot.setBounds(450, 350, 115, 20);

        lblketthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Close.png"))); // NOI18N
        lblketthuc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblketthuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblketthucMouseClicked(evt);
            }
        });
        jPanel2.add(lblketthuc);
        lblketthuc.setBounds(830, 10, 50, 50);

        lblSignIn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSignIn1.setForeground(new java.awt.Color(0, 0, 0));
        lblSignIn1.setText("REGISTRATION");
        lblSignIn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSignIn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignIn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSignIn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSignIn1MouseExited(evt);
            }
        });
        jPanel2.add(lblSignIn1);
        lblSignIn1.setBounds(570, 350, 100, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignInMouseClicked
        // TODO add your handling code here:
        dangNhap();
    }//GEN-LAST:event_lblSignInMouseClicked

    private void lblSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignInMouseEntered
        // TODO add your handling code here:


    }//GEN-LAST:event_lblSignInMouseEntered

    private void lblSignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignInMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_lblSignInMouseExited

    private void lblForgotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotMouseEntered
        // TODO add your handling code here:
   
    }//GEN-LAST:event_lblForgotMouseEntered

    private void lblForgotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotMouseExited

    }//GEN-LAST:event_lblForgotMouseExited

    private void lblketthucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblketthucMouseClicked
        // TODO add your handling code here:
        if (MsgBox.confirm(this, "Bạn Muốn Kết Thúc Chương Trình")) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblketthucMouseClicked

    private void lblSignIn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignIn1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblSignIn1MouseClicked

    private void lblSignIn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignIn1MouseEntered
        // TODO add your handling code here:
        lblSignIn.setBorder(new MatteBorder(0, 0, 1, 0, new Color(0, 153, 255)));
        lblSignIn.setForeground(new Color(0, 153, 255));
    }//GEN-LAST:event_lblSignIn1MouseEntered

    private void lblSignIn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignIn1MouseExited
        // TODO add your handling code here:
        lblSignIn.setBorder(new MatteBorder(0, 0, 0, 0, Color.BLACK));
        lblSignIn.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblSignIn1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhapDialog dialog = new DangNhapDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblForgot;
    private javax.swing.JLabel lblSignIn;
    private javax.swing.JLabel lblSignIn1;
    private javax.swing.JLabel lblketthuc;
    private javax.swing.JPanel pnSignIn;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables
}
