/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.edusys.ul;

import com.edusys.utils.MsgBox;
import com.edusys.utils.XImage;
import java.awt.Color;
import javax.swing.border.EmptyBorder;
import javax.swing.border.MatteBorder;

/**
 *
 * @author ADMIN
 */
public class RegisterJDialog extends javax.swing.JFrame {

    /**
     * Creates new form dangky
     */
    public RegisterJDialog() {
        setIconImage(XImage.getAppIcon());
        setTitle("ĐĂNG KÝ");
        initComponents();
        txtUser.setBorder(new EmptyBorder(20, 3, 10, 3));
        txtUser.setBorder(new MatteBorder(0, 0, 1, 0, new Color(0, 153, 255)));
        
        txtPass.setBorder(new EmptyBorder(20, 3, 10, 3));
        txtPass.setBorder(new MatteBorder(0, 0, 1, 0, new Color(0, 153, 255)));
        
        txtConfirmPass.setBorder(new EmptyBorder(20, 3, 10, 3));
        txtConfirmPass.setBorder(new MatteBorder(0, 0, 1, 0, new Color(0, 153, 255)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtConfirmPass = new javax.swing.JPasswordField();
        txtPass = new javax.swing.JPasswordField();
        pnSignUp = new javax.swing.JPanel();
        lblSignUp = new javax.swing.JLabel();
        lblSignIn = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 560));
        setMinimumSize(new java.awt.Dimension(900, 560));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 560));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 560));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/lg (1).png"))); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(70, 50, 260, 220);

        jLabel11.setFont(new java.awt.Font("Fz Rough Marker", 0, 80)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("DRINK DROP");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(30, 360, 352, 80);

        jLabel12.setFont(new java.awt.Font("Ethons Styles", 0, 60)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Welcome  To");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(110, 290, 200, 80);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(500, 0, 400, 560);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Close.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 50, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRATION");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 60, 270, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 130, 90, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/user.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(420, 160, 32, 40);

        txtUser.setBackground(new java.awt.Color(255, 255, 255));
        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtUser.setForeground(new java.awt.Color(0, 153, 255));
        jPanel1.add(txtUser);
        txtUser.setBounds(40, 160, 420, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 220, 90, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Confirm Password:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 310, 170, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/password.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(420, 250, 32, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/password.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(420, 340, 32, 40);

        txtConfirmPass.setBackground(new java.awt.Color(255, 255, 255));
        txtConfirmPass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtConfirmPass.setForeground(new java.awt.Color(0, 153, 255));
        jPanel1.add(txtConfirmPass);
        txtConfirmPass.setBounds(40, 340, 420, 40);

        txtPass.setBackground(new java.awt.Color(255, 255, 255));
        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPass.setForeground(new java.awt.Color(0, 153, 255));
        jPanel1.add(txtPass);
        txtPass.setBounds(40, 250, 420, 40);

        pnSignUp.setBackground(new java.awt.Color(0, 153, 255));

        lblSignUp.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblSignUp.setForeground(new java.awt.Color(255, 255, 255));
        lblSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignUp.setText("SIGN UP");
        lblSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSignUpMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnSignUpLayout = new javax.swing.GroupLayout(pnSignUp);
        pnSignUp.setLayout(pnSignUpLayout);
        pnSignUpLayout.setHorizontalGroup(
            pnSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        pnSignUpLayout.setVerticalGroup(
            pnSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(pnSignUp);
        pnSignUp.setBounds(90, 450, 320, 60);

        lblSignIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSignIn.setForeground(new java.awt.Color(0, 0, 0));
        lblSignIn.setText("SIGN IN");
        lblSignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSignInMouseExited(evt);
            }
        });
        jPanel1.add(lblSignIn);
        lblSignIn.setBounds(220, 400, 50, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Already have an account?");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 400, 170, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 560);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if (MsgBox.confirm(this, "Bạn Muốn Kết Thúc Chương Trình")) {
             System.exit(0);
         }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void lblSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignUpMouseEntered
        // TODO add your handling code here:
        pnSignUp.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_lblSignUpMouseEntered

    private void lblSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignUpMouseExited
        // TODO add your handling code here:
        pnSignUp.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_lblSignUpMouseExited

    private void lblSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignInMouseEntered
        // TODO add your handling code here:
        lblSignIn.setBorder(new MatteBorder(0, 0, 1, 0, new Color(0, 153, 255)));
        lblSignIn.setForeground(new Color(0, 153, 255));
    }//GEN-LAST:event_lblSignInMouseEntered

    private void lblSignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignInMouseExited
        // TODO add your handling code here:
        lblSignIn.setBorder(new MatteBorder(0, 0, 0, 0, Color.BLACK));
        lblSignIn.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblSignInMouseExited

    private void lblSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignInMouseClicked
        // TODO add your handling code here:
        new SignInJDialog().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblSignInMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterJDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSignIn;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JPanel pnSignUp;
    private javax.swing.JPasswordField txtConfirmPass;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
