/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.edusys.ul;

import com.edusys.utils.MsgBox;
import com.edusys.utils.XImage;
import java.awt.Color;
import javax.swing.border.EmptyBorder;
import javax.swing.border.MatteBorder;

/**
 *
 * @author ADMIN
 */
public class SignInJDialog extends javax.swing.JFrame {

    /**
     * Creates new form dangnhap
     */
    public SignInJDialog() {
        setIconImage(XImage.getAppIcon());
        setTitle("ĐĂNG NHẬP");
        initComponents();
        txtUser.setBorder(new EmptyBorder(20, 3, 10, 3));
        txtUser.setBorder(new MatteBorder(0, 0, 1, 0, new Color(0, 153, 255)));
        
        txtPass.setBorder(new EmptyBorder(20, 3, 10, 3));
        txtPass.setBorder(new MatteBorder(0, 0, 1, 0, new Color(0, 153, 255)));
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        pnSignIn = new javax.swing.JPanel();
        lblSignIn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblForgot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 558));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(900, 560));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 560));
        jPanel1.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/lg (1).png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 30, 260, 220);

        jLabel9.setFont(new java.awt.Font("Ethons Styles", 0, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Welcome Back  To");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 280, 264, 80);

        jLabel11.setFont(new java.awt.Font("Fz Rough Marker", 0, 80)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("DRINK DROP");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 360, 352, 80);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 560);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN IN");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(580, 70, 150, 48);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Username:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(440, 160, 100, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/user.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(820, 190, 32, 40);

        txtUser.setBackground(new java.awt.Color(255, 255, 255));
        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtUser.setForeground(new java.awt.Color(0, 153, 255));
        jPanel2.add(txtUser);
        txtUser.setBounds(440, 190, 420, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Password:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(440, 260, 100, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/password.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(820, 290, 40, 40);

        txtPass.setBackground(new java.awt.Color(255, 255, 255));
        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPass.setForeground(new java.awt.Color(0, 153, 255));
        txtPass.setMargin(new java.awt.Insets(2, 10, 2, 6));
        jPanel2.add(txtPass);
        txtPass.setBounds(440, 290, 420, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Close.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(840, 10, 50, 48);

        pnSignIn.setBackground(new java.awt.Color(0, 153, 255));
        pnSignIn.setMaximumSize(new java.awt.Dimension(320, 60));
        pnSignIn.setLayout(null);

        lblSignIn.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblSignIn.setForeground(new java.awt.Color(255, 255, 255));
        lblSignIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignIn.setText("SIGN IN");
        lblSignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSignInMouseExited(evt);
            }
        });
        pnSignIn.add(lblSignIn);
        lblSignIn.setBounds(0, 0, 320, 60);

        jPanel2.add(pnSignIn);
        pnSignIn.setBounds(490, 430, 320, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Close.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6);
        jLabel6.setBounds(842, 10, 48, 50);

        lblForgot.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblForgot.setForeground(new java.awt.Color(0, 0, 0));
        lblForgot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblForgot.setText("Forgot Password?");
        lblForgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblForgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblForgotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblForgotMouseExited(evt);
            }
        });
        jPanel2.add(lblForgot);
        lblForgot.setBounds(450, 350, 115, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 900, 560);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void lblSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignInMouseEntered
        // TODO add your handling code here:
        pnSignIn.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_lblSignInMouseEntered

    private void lblSignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignInMouseExited
        // TODO add your handling code here:
        pnSignIn.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_lblSignInMouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        if (MsgBox.confirm(this, "Bạn Muốn Kết Thúc Chương Trình")) {
             System.exit(0);
         }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void lblForgotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotMouseEntered
        // TODO add your handling code here:
        lblForgot.setBorder(new MatteBorder(0, 0, 1, 0, new Color(0, 153, 255)));
        lblForgot.setForeground(new Color(0, 153, 255));
    }//GEN-LAST:event_lblForgotMouseEntered

    private void lblForgotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotMouseExited
        // TODO add your handling code here:
        lblForgot.setBorder(new MatteBorder(0, 0, 0, 0, Color.BLACK));
        lblForgot.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblForgotMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInJDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblForgot;
    private javax.swing.JLabel lblSignIn;
    private javax.swing.JPanel pnSignIn;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
